### ISSUE TITLE
Unable to fix LSO on stuck partition

### ISSUE THREAD

**Issue by Zach-Johnson** [twmb/kcl#10]
Hi @twmb -

I believe I'm hitting the issue described in https://issues.apache.org/jira/browse/KAFKA-12671 and I'm attempting to resolve it without entirely deleting the topic. Just for clarity, the situation I'm in is:
- A topic with 15 partitions
- One partition (7) is apparently stuck, I can produce data transactionally to it (using franz-go, I've also tried with kafkacat with the same results) without any errors. I can see the data on the topic by specifying `read_uncommitted`, but nothing with `read_committed`.
- All other partitions are seemingly fine

I came across your notes in that Kafka issue and I'm hitting an error when attempting to resolve with `kcl admin txn unstick-lso`:

```
kcl admin txn unstick-lso <topic>
Issuing Metadata request for the topic to determine its number of partitions...
Metadata indicates that there are 15 partitions in the topic. Issuing ListOffsets request to determine which partitions may be stuck (i.e., have records)...
Looking for the last stable offset on a partition in <topic>...
Found partition 7 stuck at offset 144, looking for producer that caused this...
Found causing producer ID and epoch 2000/0, looking in __transaction_state to find its transactional id...

Found topic <topic> stuck with transactional id <txn-id>.
At this point we can attempt to unhang the transaction.
Issue AddPartitionsToTxn followed by EndTxn? [Y/n] Y
Proceeding to unstick...

Issuing AddPartitionsToTxn request to fake a new transaction...
partition in AddPartitionsToTxn had error: INVALID_PRODUCER_ID_MAPPING: The producer attempted to use a producer id which is not currently assigned to its transactional id.
```

I'm unclear how to proceed from here and was hoping you might have some ideas. I've disabled the producer that was using this transaction ID and waited for longer than `transactional.id.expiration.ms` and retried it with the same result.

**Comment by twmb** [comment]
Did your transaction get stuck from franz-go, or something else?

**Comment by Zach-Johnson** [comment]
It was from franz-go, currently v1.2.6

**Comment by twmb** [comment]
I wonder if it is from the bug that was fixed in v1.3.2. Is that transactional ID still in use?

**Comment by Zach-Johnson** [comment]
Ohhh, wow, yeah I didn't see that when I skimmed the changelog earlier, that definitely sounds like it could be it. Our application is rapidly creating/closing transactions in some cases (e.g. sometimes only a few messages per txn). If I'm understanding the changelog correctly, it sounds like errors were being swallowed?

The transactional ID _was_ still in use, I disabled the instance that was using it prior to trying this unstick-lso command though

**Comment by twmb** [comment]
Yeah, ... bad bug. From my investigation of KAFKA-12671 and recent re-investigating, this should be possible to fix by:
- reusing the same transactional ID that caused this problem
- producing to that partition
- ending the transaction

This is actually the basis for the reasoning on `EndBeginTxnUnsafe`: https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#EndBeginTxnHow

The problem I was running into with KAFKA-12671, it seems, is that I was using a random txnal ID that was only used for an integration test. Reusing the same txnal ID for a new transaction may have been able to fix the problem I was originally seeing. I plan on updating the issue again once I look into Kafka code to see why reusing the txnal ID fixes it.

Can you run that sequence of events above and see if it fixes it? Also, how many replicas does this partition have? What Kafka version are you using?

**Comment by Zach-Johnson** [comment]
So my application continued running for a time after the locking occurred, it was producing data transactionally on the same transactional ID successfully (although perhaps not if some errors were being missed). I've also now updated to franz-go 1.4.0 and produced/ended a transaction with the same ID without any result and no errors reported. So maybe something else is going on?

The partition has 2 replicas. Kafka version is 2.8.1 running on MSK.

**Comment by twmb** [comment]
Two replicas may be a bit unsafe (I usually go three -- I don't know what consistency guarantees there are at 2?). The error swallowing does make it hard to reason about if something was going wrong.

If things continued producing with the same transactional ID and the same producer ID, then I don't know what could be the problem. If it's a different producer ID now, that would be a problem and would result in INVALID_PRODUCER_ID_MAPPING, and the only way I know to resolve the issue is to ensure txnal-id+pid and then adding partitions to a transaction.

It's pretty confusing that a different producer ID was chosen though -- I thought those persisted, and then the epoch just slowly was bumped. I wonder if the transactional ID was not used for so long that it was expired internally.

**Comment by twmb** [comment]
Also, 1.3.2 should never have ran into the problem to begin with -- the problem that caused 12671 has long since been fixed.

**Comment by Zach-Johnson** [comment]
Sorry, there are 2 replicas + leader, 3 replicas total.

Yeah its a confusing issue, the producer ID thing is unclear to me as well. I'm blowing away the topic and re-running with franz-go 1.4.0. Hopefully we just don't hit the issue again.

Thanks for your help on this, I'll close this out and open something else if we hit it again.

**Comment by Zach-Johnson** [comment]
> It's pretty confusing that a different producer ID was chosen though -- I thought those persisted, and then the epoch just slowly was bumped. I wonder if the transactional ID was not used for so long that it was expired internally.

I've determined that this is what happened and I'm able to reliably reproduce the issue. The application had some instances that were occasionally idling for long periods, the transaction id (and producer id) timed out and kafka removed them, then when data came through, the error was silently swallowed since we were using an outdated version of franz-go, and then the partition locked, with seemingly no way to recover it.

On the updated version of franz-go, the situation is roughly the same, but the error is now caught properly, and the partition never locks - it just requires the producer to be re-initialized.

**Comment by twmb** [comment]
Interesting, good the new version prevents that. Though, I would expect reusing the same txnal ID would restart a new transaction and transparently recover under the hood.

Also -- do you produce once, and then only much later EndTransaction?

**Comment by Zach-Johnson** [comment]
Yeah I would have thought the same - I'm now simulating a producer "heartbeat" by occasionally beginning/producing/aborting a transaction in the case when a producer is idling for too long. This avoids the issue entirely, although this feels pretty hacky and I wish there was a nicer way to do this.

> Also -- do you produce once, and then only much later EndTransaction?

No, the EndTransaction happens immediately after the produce
