### ISSUE TITLE
Connect to kafka without config

### ISSUE THREAD

**Issue by cloud-66** [twmb/kcl#30]
Hello. I'm used to using kafka utils from kafka distribution like
```
./kafka-topics.sh --bootstrap-server hostname:9092 --describe
```
Is there way to use kcl without creating any config ? Maybe it's not clear for me how to create this config, how to use it. I just want to connect and get what i want from kafka by single command.
Thank you.

**Comment by twmb** [comment]
Yes, `kcl` provides both `--no-config-file` to force disabling a configuration file, and `-X` to set all configuration options. See the help text in `kcl myconfig help` to see how to use `-X`.
