### ISSUE TITLE
Tag 0.4.0

### ISSUE THREAD

**Issue by AnatolyRugalev** [twmb/kcl#4]
Hey!

Can you please tag current master with the next version?

We are using master branch now to work with AWS IAM

**Comment by twmb** [comment]
Sure thing! I nearly released last week actually, then decided to wait for ...something...
I'll take a look to see if franz-go has something outsanding I need to tag and then tag this based off of the latest franz-go as well.

**Comment by twmb** [comment]
I did change how AWS_MSK_IAM was supported between v0.3.0 to tip, the latest changes just pull in your ~/.aws/credentials (I think the aws-sdk-go lib may also support env vars). I hope that's ok? If not, I can tag v0.4.1 to optionally specify the access/secret key in the kcl config directly as well.

**Comment by twmb** [comment]
[v0.4.0](https://github.com/twmb/kcl/releases/tag/v0.4.0) now exists! Again let me know if the msk changes are suitable, if not I can always add the ability to specify the access/secret keys directly in kcl as well.

**Comment by AnatolyRugalev** [comment]
Perfect, thanks! Auto discovery works for us, no need in extra overrides 🙂 

Great work btw 👍

**Comment by twmb** [comment]
Awesome, thanks! Please let me know if there's any features that'd be very useful for you, or some api usage cleanup.

And if you want to pass along a recommendation for kcl to anybody else, that' may drive improvements and traffic :sweat_smile:
