### ISSUE TITLE
Alter partitions support

### ISSUE THREAD

**Issue by nmarian85** [twmb/kcl#42]
Hello there. I wanted to take the opportunity to say thank you for doing this work and easing kafka configurations for us all. I had a question rather than an issue: I was trying to add partitions to a topic. 52 partitions to be more precise. I was looking at the add-partitions subcommand but it seems tedious to build the combinations required by the subcommand. Did I maybe miss smth and there is a simpler way for that? Asking since in the end I went back to the kafka-topics cli and used the alter command.

Many thanks.

**Comment by twmb** [comment]
The simple way to do it now is actually in rpk, which I worked on for a while:

```
rpk topic add-partitions foo --num 52
```

I really recommend rpk where possible. The add-partitions command doesn't have much code; the `kadm` package could be added into kcl and replace the existing kcl add-partitions command -- but I'll leave that as an exercise for you if you're interested ;).

Closing for now, but lmk what you think -- and I'll review a PR if you open one.
