### ISSUE TITLE
UserCRAM was created success but cannot authenticate to cluster

### ISSUE THREAD

**Issue by tommy04062019** [twmb/kcl#9]
Command:
```
/kcl --config-path config.toml admin user-scram alter --set user=user1,mechanism=scram-sha-512,iterations=8192,password=123456
```
Error:
```
org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512
```

**Comment by twmb** [comment]
What's the output of running the first command?

**Comment by tommy04062019** [comment]
> What's the output of running the first command?

It's here:
```
{
  "Version": 0,
  "ThrottleMillis": 0,
  "Results": [
    {
      "User": "user1",
      "ErrorCode": 0,
      "ErrorMessage": "",
      "UnknownTags": {}
    }
  ],
  "UnknownTags": {}
}
```

**Comment by tommy04062019** [comment]
Hi @twmb have u checked this? Your tool is great, It only lacks this part

**Comment by twmb** [comment]
Sorry, kcl is a bit lower priority for me at the moment. Everything above looks correct: what's the output of using the password? I remember when I tried this a bit ago that it was working. I could potentially try again -- not sure if I have a docker compose stashed around that enables the authorizer.

**Comment by tommy04062019** [comment]
> Sorry, kcl is a bit lower priority for me at the moment. Everything above looks correct: what's the output of using the password? I remember when I tried this a bit ago that it was working. I could potentially try again -- not sure if I have a docker compose stashed around that enables the authorizer.

Ahh!, I knew where your code wrong.
```
case "pasword":
  password = v
```
You miss `s` when check key `password`. After correcting, it works fine for me now. Thanks for responding

**Comment by twmb** [comment]
Looks like an easy fix, mind opening a PR?
